---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: git-clone
spec:
  params:
    - name: url
      type: string
      description: The URL to clone from
    - name: revision
      type: string
      description: Revision to checkout (branch, tag, sha, ref, etc...)
      default: ""
    - name: subdirectory
      type: string
      description: >
        Subdirectory inside the `output` Workspace to clone the repo into
      default: ""
    - name: deleteExisting
      type: string
      description: >
        Whether to clean out the contents of the destination directory if
        it already exists before cloning
      default: "true"
    - name: verbose
      type: string
      description: Whether this task script should show verbose output
      default: "false"
  workspaces:
    - name: output
      description: Workspace where the git repository will be cloned into
  steps:
    - name: clone
      image: quay.io/hacbs-release/release-utils
      script: |
        #!/usr/bin/env sh
        set -eu

        if [ "$(params.verbose)" = "true" ]; then
          set -x
        fi

        CHECKOUT_DIR="$(workspaces.output.path)/$(params.subdirectory)"

        if [ "$(params.deleteExisting)" = "true" ]; then
          if [ -d "${CHECKOUT_DIR}" ] ; then
            # Delete non-hidden files and directories
            rm -rf "${CHECKOUT_DIR:?}"/*
            # Delete files and directories starting with . but excluding ..
            rm -rf "${CHECKOUT_DIR}"/.[!.]*
            # Delete files and directories starting with .. plus
            # any other character.
            rm -rf "${CHECKOUT_DIR}"/..?*
          fi
        fi

        if [ -z "$(params.revision)" ]; then
          git clone "$(params.url)" "${CHECKOUT_DIR}"
        else
          git clone -b "$(params.revision)" "$(params.url)" "${CHECKOUT_DIR}"
        fi
