---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: skopeo-copy-task
spec:
  params:
    - name: srcImageURL
      description: Source URL
      type: string
      default: ""
    - name: destImageURL
      description: Destination URL
      type: string
      default: ""
    - name: srcToken
      description: Robot bearer token for source
      type: string
      default: ""
    - name: destToken
      description: Robot bearer token for destination
      type: string
      default: ""

  steps:
    - name: skopeo-copy
      image: quay.io/skopeo/stable:v1.7.0
      script: |
        if [[ -z "$(params.srcImageURL)" && -z "$(params.destImageURL)" ]]
        then
          exit 1 # Missing URL parameters
        elif [[ -z "$(params.srcToken)" && -z "$(params.destToken)" ]]
        then
          exit 2 # Missing TOKEN parameters
        fi
        srcDigest=$(skopeo inspect "$(params.srcImageURL 2>/dev/null)" | jq -r ".Digest")
        destDigest=$(skopeo inspect "$(params.destImageURL 2>/dev/null)" | jq -r ".Digest")
        case "$destDigest" in
          ("$srcDigest")
            exit 0  # Noop
            ;;
          (*)
            skopeo copy \
              --all \
              --preserve-digests \
              --src-registry-token  "$(params.srcToken)" \
              --dest-registry-token "$(params.destToken)" \
              "$(params.srcImageURL)" \
              "$(params.destImageURL)" ;
            ;;
        esac
